// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list_upcoming_events.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
import { z } from "npm:zod@^3.25.76";
var list_upcoming_events_default = defineTool({
  name: "list_upcoming_events",
  title: "Listar pr\xF3ximos eventos",
  description: "Retorna os pr\xF3ximos eventos publicados da MDAccula (S\xE3o Paulo), ordenados por data crescente. Inclui t\xEDtulo, local, data, g\xEAneros e link do evento.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(10).describe("Quantidade m\xE1xima de eventos a retornar (1-50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const { data, error } = await supabase.from("events").select(
      "id, title, subtitle, slug, venue, address, location_city, location_state, date, end_date, time, genres, ticket_link, image_url"
    ).eq("status", "published").gte("date", today).order("date", { ascending: true }).limit(limit);
    if (error) {
      return { content: [{ type: "text", text: `Erro: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { events: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get_event.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.97.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_event_default = defineTool2({
  name: "get_event",
  title: "Detalhes de um evento",
  description: "Retorna os detalhes completos de um evento MDAccula pelo slug (ex.: 'parador-reveillon'). Inclui line-up, descri\xE7\xE3o, hor\xE1rios e link de ingresso.",
  inputSchema: {
    slug: z2.string().trim().min(1).describe("Slug do evento (URL).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("events").select(
      "id, title, subtitle, slug, venue, address, location_city, location_state, date, end_date, time, end_time, genres, lineup, description, schedule, ticket_link, vip_link, image_url, latitude, longitude"
    ).eq("slug", slug).eq("status", "published").maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: `Erro: ${error.message}` }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: `Evento '${slug}' n\xE3o encontrado.` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { event: data }
    };
  }
});

// src/lib/mcp/tools/list_blog_posts.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.97.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_blog_posts_default = defineTool3({
  name: "list_blog_posts",
  title: "Listar posts do blog",
  description: "Lista os posts publicados no blog da MDAccula, do mais recente ao mais antigo. Suporta filtro por categoria e busca por palavra-chave.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).default(10),
    category: z3.string().trim().optional().describe("Filtrar por categoria (opcional)."),
    search: z3.string().trim().optional().describe("Buscar por termo no t\xEDtulo ou resumo (opcional).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, category, search }) => {
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let query = supabase.from("blog_posts").select("id, title, slug, excerpt, category, image_url, views, likes, published_at").eq("published", true).order("published_at", { ascending: false }).limit(limit);
    if (category) query = query.eq("category", category);
    if (search) query = query.or(`title.ilike.%${search}%,excerpt.ilike.%${search}%`);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: `Erro: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { posts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get_blog_post.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.97.0";
import { z as z4 } from "npm:zod@^3.25.76";
var get_blog_post_default = defineTool4({
  name: "get_blog_post",
  title: "Detalhes de um post do blog",
  description: "Retorna o conte\xFAdo completo de um post publicado no blog MDAccula, buscado pelo slug.",
  inputSchema: {
    slug: z4.string().trim().min(1).describe("Slug do post (URL).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const supabase = createClient4(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("blog_posts").select(
      "id, title, slug, excerpt, content, category, image_url, views, likes, published_at, meta_description"
    ).eq("slug", slug).eq("published", true).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: `Erro: ${error.message}` }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: `Post '${slug}' n\xE3o encontrado.` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { post: data }
    };
  }
});

// src/lib/mcp/tools/list_links.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.97.0";
var list_links_default = defineTool5({
  name: "list_links",
  title: "Listar links p\xFAblicos (Linktree)",
  description: "Lista os links p\xFAblicos ativos da p\xE1gina de links da MDAccula (estilo Linktree), agrupados por se\xE7\xE3o.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const supabase = createClient5(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await supabase.from("link_groups").select(
      "id, name, slug, display_order, enabled, custom_links(id, title, subtitle, url, is_featured, display_order, enabled)"
    ).eq("enabled", true).order("display_order", { ascending: true });
    if (error) {
      return { content: [{ type: "text", text: `Erro: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { groups: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "mdaccula-mcp",
  title: "MDAccula MCP",
  version: "0.1.0",
  instructions: "Ferramentas p\xFAblicas da MDAccula (ag\xEAncia de m\xFAsica eletr\xF4nica em S\xE3o Paulo). Use `list_upcoming_events` e `get_event` para eventos, `list_blog_posts` e `get_blog_post` para artigos do blog, e `list_links` para os links oficiais (Linktree). Todos os dados retornados s\xE3o p\xFAblicos.",
  tools: [list_upcoming_events_default, get_event_default, list_blog_posts_default, get_blog_post_default, list_links_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
