import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import { CheckCircle, Loader2, AlertCircle, Upload } from "lucide-react";
import Papa from "papaparse";

interface ImportStep {
  table: string;
  csvFile: string;
  label: string;
  count: string;
  batchSize: number;
  status: "pending" | "running" | "done" | "error";
  result?: string;
  progress?: string;
}

const IMPORT_STEPS: Omit<ImportStep, "status">[] = [
  { table: "blog_posts", csvFile: "/import/blog_posts.csv", label: "Blog Posts (UPSERT)", count: "~113", batchSize: 10 },
  { table: "events", csvFile: "/import/events.csv", label: "Events", count: "~141", batchSize: 20 },
  { table: "custom_links", csvFile: "/import/custom_links.csv", label: "Custom Links", count: "~180", batchSize: 20 },
  { table: "ai_generated_posts", csvFile: "/import/ai_generated_posts.csv", label: "AI Generated Posts", count: "~117", batchSize: 20 },
  { table: "fix_urls", csvFile: "", label: "Corrigir URLs de imagens", count: "todas tabelas", batchSize: 1 },
];

export default function DataImport() {
  const [steps, setSteps] = useState<ImportStep[]>(
    IMPORT_STEPS.map(s => ({ ...s, status: "pending" as const }))
  );
  const [running, setRunning] = useState(false);

  const updateStep = (index: number, update: Partial<ImportStep>) => {
    setSteps(prev => prev.map((s, i) => i === index ? { ...s, ...update } : s));
  };

  const parseCSVFile = async (csvFile: string): Promise<Record<string, string>[]> => {
    const resp = await fetch(csvFile);
    if (!resp.ok) throw new Error(`Failed to fetch ${csvFile}: ${resp.status}`);
    const csvText = await resp.text();

    return new Promise((resolve, reject) => {
      Papa.parse<Record<string, string>>(csvText, {
        header: true,
        skipEmptyLines: true,
        dynamicTyping: false,
        complete: (results) => {
          if (results.errors.length > 0) {
            console.warn("CSV parse warnings:", results.errors);
          }
          resolve(results.data);
        },
        error: (err: Error) => reject(err),
      });
    });
  };

  const importTable = async (index: number) => {
    const step = steps[index];
    updateStep(index, { status: "running", result: undefined, progress: undefined });

    try {
      // fix_urls doesn't need CSV
      if (step.table === "fix_urls") {
        updateStep(index, { progress: "Corrigindo URLs..." });
        const { data, error } = await supabase.functions.invoke("import-csv-data", {
          body: { table: "fix_urls", records: [] },
        });
        if (error) throw error;
        updateStep(index, {
          status: data?.success === false ? "error" : "done",
          result: JSON.stringify(data, null, 2),
          progress: undefined,
        });
        return;
      }

      // 1. Parse CSV with PapaParse
      updateStep(index, { progress: "Parsing CSV..." });
      let records = await parseCSVFile(step.csvFile);

      // Remove search_vector from blog_posts (regenerated by trigger)
      if (step.table === "blog_posts") {
        records = records.map(r => {
          const { search_vector, ...rest } = r;
          return rest;
        });
      }

      console.log(`Parsed ${records.length} records for ${step.table}`, records[0]);

      // 2. Send in batches
      const { batchSize } = step;
      let totalInserted = 0;
      const errors: string[] = [];
      const totalBatches = Math.ceil(records.length / batchSize);

      for (let i = 0; i < records.length; i += batchSize) {
        const batchNum = Math.floor(i / batchSize) + 1;
        updateStep(index, { progress: `Batch ${batchNum}/${totalBatches}...` });

        const batch = records.slice(i, i + batchSize);
        const { data, error } = await supabase.functions.invoke("import-csv-data", {
          body: { table: step.table, records: batch },
        });

        if (error) {
          errors.push(`Batch ${batchNum}: ${error.message}`);
        } else if (data?.success === false) {
          errors.push(`Batch ${batchNum}: ${data.error}`);
        } else {
          totalInserted += batch.length;
        }
      }

      const resultMsg = JSON.stringify({
        total: records.length,
        inserted: totalInserted,
        errors: errors.length,
        errorDetails: errors.length > 0 ? errors : undefined,
      }, null, 2);

      updateStep(index, {
        status: errors.length > 0 && totalInserted === 0 ? "error" : "done",
        result: resultMsg,
        progress: undefined,
      });

      if (errors.length > 0) {
        toast.error(`${step.label}: ${errors.length} erros de ${totalBatches} batches`);
      } else {
        toast.success(`${step.label}: ${totalInserted} registros importados!`);
      }
    } catch (err: any) {
      updateStep(index, { status: "error", result: err.message, progress: undefined });
      toast.error(`${step.label}: ${err.message}`);
    }
  };

  const runAll = async () => {
    setRunning(true);
    for (let i = 0; i < steps.length; i++) {
      if (steps[i].status === "done") continue;
      await importTable(i);
    }
    setRunning(false);
    toast.success("Importação completa!");
  };

  return (
    <div className="container mx-auto py-8 px-4 max-w-3xl">
      <h1 className="text-2xl font-bold mb-6">Importação de Dados</h1>
      <p className="text-muted-foreground mb-6">
        Parse CSV no frontend com PapaParse → envia JSON para edge function → upsert no banco.
      </p>

      <div className="space-y-4 mb-6">
        {steps.map((step, i) => (
          <Card key={step.table} className={step.status === "done" ? "border-green-500" : step.status === "error" ? "border-red-500" : ""}>
            <CardHeader className="py-3 px-4">
              <div className="flex items-center justify-between">
                <CardTitle className="text-base flex items-center gap-2">
                  {step.status === "done" && <CheckCircle className="h-5 w-5 text-green-500" />}
                  {step.status === "running" && <Loader2 className="h-5 w-5 animate-spin" />}
                  {step.status === "error" && <AlertCircle className="h-5 w-5 text-red-500" />}
                  {step.status === "pending" && <Upload className="h-5 w-5 text-muted-foreground" />}
                  {step.label} ({step.count})
                  {step.progress && <span className="text-sm text-muted-foreground ml-2">{step.progress}</span>}
                </CardTitle>
                <Button
                  size="sm"
                  variant={step.status === "done" ? "outline" : "default"}
                  onClick={() => importTable(i)}
                  disabled={running}
                >
                  {step.status === "done" ? "Re-importar" : "Importar"}
                </Button>
              </div>
            </CardHeader>
            {step.result && (
              <CardContent className="py-2 px-4">
                <pre className="text-xs bg-muted p-2 rounded overflow-auto max-h-40">{step.result}</pre>
              </CardContent>
            )}
          </Card>
        ))}
      </div>

      <Button onClick={runAll} disabled={running} size="lg" className="w-full">
        {running ? <><Loader2 className="mr-2 h-4 w-4 animate-spin" /> Importando...</> : "🚀 Importar Tudo Sequencialmente"}
      </Button>
    </div>
  );
}
